theme: jekyll-theme-cayman
description: "Nexus of AI in Healthcare"

# Optional: if you want a navigation menu
header_pages:
  - title: "Home"
    url: "/"
  - title: "Professor"
    url: "/professor"
  - title: "Team"
    url: "/team"
  - title: "Research"
    url: "/research"
  - title: "Publication"
    url : "https://scholar.google.com/citations?user=VsIv9g0AAAAJ&hl=en"
  - title: "Lectures"
    url: "/lectures"
  - title: "Funding"
    url: "/funding"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
